config/routes.rb
DebateJudge::Application.routes.draw do

  resources :users, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: :login

  root to: 'main#index'
  match '*path', to: 'main#index'

  scope "api" do
    resources :tournaments
    resources :rounds
    resources :contentions
  end

end

app/models/contention.rb
class Contention < ActiveRecord::Base
  attr_accessible :speech_type, :contention, :refuted, :refuted_by

  belongs_to :round
  belongs_to :user

  validates :speech_type, :contention, presence: true

  after_save :update_round
  after_destroy :update_round

  protected
  def update_round
    Round.find(self.round_id).update_attributes(updated_at: Time.now)
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :round_num, :event, :notes, :updated_at

  belongs_to :tournament
  belongs_to :user
  has_many :contentions, dependent: :destroy

  validates :round_num, :event, presence: true
  validates_uniqueness_of :round_num, :scope => [:event, :tournament_id]

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :tournament, :school, :date

  belongs_to :user
  has_many :rounds, dependent: :destroy

  validates :tournament, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :tournaments
  has_many :rounds, through: :tournaments
  has_many :contentions, through: :rounds

  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_create :create_remember_token
  after_create :send_welcome_email

  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: valid_email_regex },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  def create_remember_token
    while User.exists?(remember_token: self.remember_token)
      self.remember_token = SecureRandom.urlsafe_base64
    end
  end

  def send_welcome_email
    UserNotifier.signup_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  before_filter :authorize
  
  def authorize
    signed_in_user
  end
end

app/controllers/contentions_controller.rb
class ContentionsController < ApplicationController
  respond_to :json

  def index
    respond_with User.find(current_user.id).contentions
    # respond_with User.find(current_user.id).contentions.where(round_id: params[:round_id])
  end

  def show
    if User.find(current_user.id).contentions.find(params[:id]).errors.empty?
      respond_with Contention.find(params[:id])
    else
      render json: {status: 'error'}, status: 500
    end
  end

  def create
    round = Round.find(params[:round_id])
    contention = round.contentions.create(params.slice(:speech_type, :contention))

    if contention.errors.empty?
      respond_with contention
    else
      render json: {status: 'error'}, status: 500
    end
  end

  def update
    respond_with Contention.update(params[:id], params.slice(:contention, :refuted))
  end

  def destroy
    if User.find(current_user.id).contentions.find(params[:id]).errors.empty?
      respond_with Contention.destroy(params[:id])
    else
      render json: {status: 'error'}, status: 500
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :authorize, only: [:index]

  def index
    gon.currentUserID = current_user.try(:id)
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  respond_to :json

  def index
    if current_user
      respond_with User.find(current_user.id).rounds
    else
      render json: {status: 'error'}, status: 500
    end
  end

  def show
    if User.find(current_user.id).rounds.find(params[:id]).errors.empty?
      respond_with Round.find(params[:id])
    else
      render json: {status: 'error'}, status: 500
    end
  end

  def create
    round = Tournament.find(params[:tournament_id]).rounds.create(params[:round])

    if round.errors.empty?
      respond_with round
    else
      round.destroy()
      respond_with round
    end
  end

  def update
    if params[:updated_at]
      Round.update(params[:id], params[:updated_at])
    else
      respond_with Round.update(params[:id], params[:round])
    end
  end

  def destroy
    respond_with Round.destroy(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]
  respond_to :html, :json

  def new
    gon.currentUserID = current_user.try(:id)
  end

  def create
    @user = User.find_by_email(params[:email])

    unless @user
      flash.now[:error] = "A user with that email does not exist."
      render action: "new"
      return
    end

    if @user && @user.authenticate(params[:password])
      sign_in(@user, params[:remember])
      redirect_to tournaments_path, :notice => "You have successfully logged in."
    else
      flash.now[:error] = "Password is incorrect."
      render action: "new"
    end
  end

  def destroy
    sign_out
    redirect_to root_path, :notice => "You have successfully logged out."
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  respond_to :json

  def index
    if current_user
      respond_with User.find(current_user.id).tournaments
    else
      render json: {status: 'error'}, status: 500
    end
  end

  def show
    respond_with Tournament.find(params[:id])
  end

  def create
    tournament = User.find(current_user.id).tournaments.create(params.slice(:tournament, :school, :date))

    if tournament.errors.empty?
      respond_with tournament
    else
      respond_with Tournament.create(params.slice(:tournament, :school, :date))
    end
  end

  def update
    respond_with Tournament.update(params[:id], params[:tournament])
  end

  def destroy
    respond_with Tournament.destroy(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]
  respond_to :json

  def show
    respond_with User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])

    if @user.errors.empty?
      sign_in(@user)
      respond_with @user
    else
      respond_with User.create(params[:user])
    end
  end

  def update
    respond_with User.find(current_user).update_attributes(params.slice(:name, :email))
  end

  def destroy
    respond_with User.destroy(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/contentions_helper.rb
module ContentionsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user, remember=false)
    if remember
      cookies.permanent[:remember_token] = user.remember_token
    else
      cookies[:remember_token] = user.remember_token
    end
    # calls the current_user method below
    current_user = user
  end

  def signed_in?
    !!current_user
  end

  def signed_in_user
    unless signed_in?
      #session[:return_to] = request.url
      redirect_to login_path, error: "Please sign in to see this page."
    end
  end

  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.where(remember_token: cookies[:remember_token]).first
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.haml
.container
  .row
    - if flash[:error]
      #error-notice.alert.alert-danger= flash[:error]
    - if flash[:notice]
      #error-notice.alert.alert-success.alert-dismissable{role: "alert"}
        %button.close{type: "button", data: {dismiss: "alert"}, aria: {label: "close"}}
          %span{aria: {hidden: "true"}} &times;
        = flash[:notice]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arbitr</title>
  <%= include_gon(:camel_case => true, :watch => true) %>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <link href="/assets/application.css" media="all" rel="stylesheet" type="text/css" >
  <script src="/assets/application.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'main/navbar' %>

  <%= render 'layouts/errors' %>  

  <%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46570104-1', 'arbitr.herokuapp.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/user_notifier.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html"; charset="UTF-8", http-equiv="content-type">
  </head>
  <body>
    <style>
      div {
        font-family: 'Helvetica', 'Arial', sans-serif;
        font-size: 0.9em;
        margin-left: 5%;
        margin-right: 5%;
      }
    </style>

    <%= yield %>

  </body>
</html>

app/views/main/_navbar.html.haml
.navbar.navbar-default.navbar-static-top#navbar{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: ".navbar-collapse"}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to("Arbitr", root_path, {class: "navbar-brand"})
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        // %li
        //  %a{href: "#about"} About
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
              %span.glyphicon.glyphicon-user
              Account
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to("My Tournaments", tournaments_path)
              %li
                = link_to("Edit Account", edit_user_path(current_user))
              %li.divider
              %li
                = link_to("Sign Out", session_path(current_user), method: :delete)
        - else
          %li
            = link_to("Sign Up", new_user_path)
          %li
            = link_to("Sign In", login_path)

app/views/main/index.html.haml
%div#main
  .jumbotron
    .container.text-center
      %h1.logo Welcome to Arbitr
      %p A simple and intuitive way to flow a high school debate round.
      %p
        = link_to("Sign Up", new_user_path, class: "btn btn-default btn-lg", role: "button")
        = link_to("Try Demo", sessions_path(email: "test@amy-mac.com", password: "foobarbaz"), method: :post, class: "btn btn-default btn-lg")

  .container.intro
    .row
      .col-xs-12.col-md-4
        %h2
          %span.glyphicon.glyphicon-list
          No More Mess
        %p Arbitr keeps your debate flows organized with neat columns and contentions that can be edited instead of crossed out.

      .col-xs-12.col-md-4
        %h2
          %span.glyphicon.glyphicon-time
          Saves Time
        %p No more setting up written templates yourself. Arbitr has ready-made layouts for Lincoln Douglas, Parli, Policy, and Public Forum events.


      .col-xs-12.col-md-4
        %h2
          %span.glyphicon.glyphicon-globe
          Access Anywhere
        %p Easily keep track of the tournaments that you've done and refer back to previous debate rounds.

  %footer
    .container
      .row
        .col-xs-12
          %p Brought to you by #{link_to("Team MegaMacKinnotron", "http://amy-mac.com", data: {toggle: "tooltip", placement: "right"}, title: "Jesse and Amy MacKinnon")}

%div#round_page

/ General Use Modal
.modal.fade#myModal{ tabindex: "-1", role: "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => true }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ type: "button", "data-dismiss" => "modal", "aria-hidden" => true} &times;
        %h4.modal-title#myModalLabel
      .modal-body

app/views/user_notifier/signup_email.html.erb
<div>
  <p>
    Greetings <%= @user.name.capitalize %>,
  </p>
</div>

<div>
  <p>
    Thank you for signing up for <%= link_to "Arbitr", "http://usearbitr.com" %>. We hope this web application makes the debate flowing process a little less frustrating for you. We are working hard to make this app better all the time and rely on feedback from our users. If you have any suggestions or would like to report any bugs, please contact us.
  </p>
  <p>
    Otherwise, we'll leave you alone. Happy debating!
  </p>
</div>

<div>
  <p>
    Yours truly,<br>
    Team MegaMackinnotron
  </p>
</div>

app/views/user_notifier/signup_email.text.erb
Thank you for signing up for <%= link_to "Arbitr", "http://usearbitr.com" %>. We hope this web application makes the debate flowing process a little less frustrating for you. We are working hard to make this app better all the time and rely on feedback from our users. If you have any suggestions or would like to report any bugs, please contact us.

Otherwise, we'll leave you alone. Happy debating!

Yours truly,
Team MegaMackinnotron

app/views/users/new.html.haml
%h2 Sign Up

=form_for @user do |f|
  =f.label :name
  =f.text_field :name, required: true, placeholder: "Name"

  =f.label :email
  =f.email_field :email, required: true, placeholder: "Email address"

  =f.label :password
  =f.password_field :password, required: true, placeholder: "Password"

  =f.label :password_confirmation
  =f.password_field :password_confirmation, required: true, placeholder: "Confirm password"

  =f.submit "Submit"